server.port: 8080

app.host: http://localhost:8080

spring:
  h2.console.enabled: true

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:

  devtools.livereload.enabled: true
  freemarker.cache: false
  thymeleaf.cache: false

local.filesystem.uploadPath: C:\Users\김시호\Desktop\개인 폴더

logging:
  level:
    me.blog.anabada: debug

